from PyQt5 import QtCore, QtGui, QtWidgets
import os
PATH = r"E:\Abhishek\Capstone phase 2\FINAL\FINAL"

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(1920, 1000)
        main.setAutoFillBackground(False)
        main.setStyleSheet("QLabel { font:  20pt \"Times New Roman\";} QPushButton { font: 20pt \"Times New Roman\"; }")
        self.layoutWidget = QtWidgets.QWidget(main)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1921, 1001))
        self.layoutWidget.setObjectName("layoutWidget")
        self.MainVBox = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.MainVBox.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.MainVBox.setContentsMargins(0, 0, 0, 0)
        self.MainVBox.setSpacing(0)
        self.MainVBox.setObjectName("MainVBox")
        self.TitleFrame = QtWidgets.QFrame(self.layoutWidget)
        self.TitleFrame.setStyleSheet("background-color: rgb(73, 97, 255);")
        self.TitleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TitleFrame.setObjectName("TitleFrame")
        self.title = QtWidgets.QLabel(self.TitleFrame)
        self.title.setGeometry(QtCore.QRect(0, 0, 1920, 150))
        self.title.setStyleSheet("font: 40pt \"Times New Roman\";")
        self.title.setScaledContents(True)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        self.MainVBox.addWidget(self.TitleFrame)
        self.TypesFrame = QtWidgets.QFrame(self.layoutWidget)
        self.TypesFrame.setStyleSheet("background-color: rgb(255, 170, 67);")
        self.TypesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TypesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TypesFrame.setObjectName("TypesFrame")
        self.widget = QtWidgets.QWidget(self.TypesFrame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1921, 151))
        self.widget.setObjectName("widget")
        self.HBox = QtWidgets.QHBoxLayout(self.widget)
        self.HBox.setContentsMargins(0, 0, 0, 0)
        self.HBox.setSpacing(0)
        self.HBox.setObjectName("HBox")
        self.threeVBox = QtWidgets.QVBoxLayout()
        self.threeVBox.setSpacing(0)
        self.threeVBox.setObjectName("threeVBox")
        self.intersection_3 = QtWidgets.QLabel(self.widget)
        self.intersection_3.setAlignment(QtCore.Qt.AlignCenter)
        self.intersection_3.setObjectName("intersection_3")
        self.threeVBox.addWidget(self.intersection_3)
        self.threeButtons = QtWidgets.QHBoxLayout()
        self.threeButtons.setSpacing(0)
        self.threeButtons.setObjectName("threeButtons")
        self.ann_3 = QtWidgets.QPushButton(self.widget)
        self.ann_3.setMinimumSize(QtCore.QSize(0, 70))
        self.ann_3.setIconSize(QtCore.QSize(20, 20))
        self.ann_3.setObjectName("ann_3")

        self.ann_3.clicked.connect(lambda: self.btn_ann("3-way"))

        self.threeButtons.addWidget(self.ann_3)
        self.cnn_3 = QtWidgets.QPushButton(self.widget)
        self.cnn_3.setMinimumSize(QtCore.QSize(0, 70))
        self.cnn_3.setObjectName("cnn_3")

        self.cnn_3.clicked.connect(lambda: self.btn_cnn("3-way"))

        self.threeButtons.addWidget(self.cnn_3)
        self.threeVBox.addLayout(self.threeButtons)
        self.HBox.addLayout(self.threeVBox)
        self.fourVBox = QtWidgets.QVBoxLayout()
        self.fourVBox.setSpacing(0)
        self.fourVBox.setObjectName("fourVBox")
        self.intersection_4 = QtWidgets.QLabel(self.widget)
        self.intersection_4.setAlignment(QtCore.Qt.AlignCenter)
        self.intersection_4.setObjectName("intersection_4")
        self.fourVBox.addWidget(self.intersection_4)
        self.fourButtons = QtWidgets.QHBoxLayout()
        self.fourButtons.setSpacing(0)
        self.fourButtons.setObjectName("fourButtons")
        self.ann_4 = QtWidgets.QPushButton(self.widget)
        self.ann_4.setMinimumSize(QtCore.QSize(0, 70))
        self.ann_4.setIconSize(QtCore.QSize(20, 20))
        self.ann_4.setObjectName("ann_4")

        self.ann_4.clicked.connect(lambda: self.btn_ann("4-way"))

        self.fourButtons.addWidget(self.ann_4)
        self.cnn_4 = QtWidgets.QPushButton(self.widget)
        self.cnn_4.setMinimumSize(QtCore.QSize(0, 70))
        self.cnn_4.setObjectName("cnn_4")

        self.cnn_4.clicked.connect(lambda: self.btn_cnn("4-way"))

        self.fourButtons.addWidget(self.cnn_4)
        self.fourVBox.addLayout(self.fourButtons)
        self.HBox.addLayout(self.fourVBox)
        self.fiveVBox = QtWidgets.QVBoxLayout()
        self.fiveVBox.setSpacing(0)
        self.fiveVBox.setObjectName("fiveVBox")
        self.intersection_5 = QtWidgets.QLabel(self.widget)
        self.intersection_5.setAlignment(QtCore.Qt.AlignCenter)
        self.intersection_5.setObjectName("intersection_5")
        self.fiveVBox.addWidget(self.intersection_5)
        self.fiveButtons = QtWidgets.QHBoxLayout()
        self.fiveButtons.setSpacing(0)
        self.fiveButtons.setObjectName("fiveButtons")
        self.ann_5 = QtWidgets.QPushButton(self.widget)
        self.ann_5.setMinimumSize(QtCore.QSize(0, 70))
        self.ann_5.setIconSize(QtCore.QSize(20, 20))
        self.ann_5.setObjectName("ann_5")

        self.ann_5.clicked.connect(lambda: self.btn_ann("5-way"))

        self.fiveButtons.addWidget(self.ann_5)
        self.cnn_5 = QtWidgets.QPushButton(self.widget)
        self.cnn_5.setMinimumSize(QtCore.QSize(0, 70))
        self.cnn_5.setObjectName("cnn_5")

        self.cnn_5.clicked.connect(lambda: self.btn_cnn("5-way"))

        self.fiveButtons.addWidget(self.cnn_5)
        self.fiveVBox.addLayout(self.fiveButtons)
        self.HBox.addLayout(self.fiveVBox)
        self.doubleVBox = QtWidgets.QVBoxLayout()
        self.doubleVBox.setSpacing(0)
        self.doubleVBox.setObjectName("doubleVBox")
        self.intersection_double = QtWidgets.QLabel(self.widget)
        self.intersection_double.setAlignment(QtCore.Qt.AlignCenter)
        self.intersection_double.setObjectName("intersection_double")
        self.doubleVBox.addWidget(self.intersection_double)
        self.doubleButtons = QtWidgets.QHBoxLayout()
        self.doubleButtons.setSpacing(0)
        self.doubleButtons.setObjectName("doubleButtons")
        self.ann_double = QtWidgets.QPushButton(self.widget)
        self.ann_double.setMinimumSize(QtCore.QSize(0, 70))
        self.ann_double.setIconSize(QtCore.QSize(20, 20))
        self.ann_double.setObjectName("ann_double")

        self.ann_double.clicked.connect(lambda: self.btn_ann("double"))

        self.doubleButtons.addWidget(self.ann_double)
        self.cnn_double = QtWidgets.QPushButton(self.widget)
        self.cnn_double.setMinimumSize(QtCore.QSize(0, 70))
        self.cnn_double.setObjectName("cnn_double")

        self.cnn_double.clicked.connect(lambda: self.btn_cnn("double"))

        self.doubleButtons.addWidget(self.cnn_double)
        self.doubleVBox.addLayout(self.doubleButtons)
        self.HBox.addLayout(self.doubleVBox)
        self.complexVBox = QtWidgets.QVBoxLayout()
        self.complexVBox.setSpacing(0)
        self.complexVBox.setObjectName("complexVBox")
        self.intersection_complex = QtWidgets.QLabel(self.widget)
        self.intersection_complex.setAlignment(QtCore.Qt.AlignCenter)
        self.intersection_complex.setObjectName("intersection_complex")
        self.complexVBox.addWidget(self.intersection_complex)
        self.complexButtons = QtWidgets.QHBoxLayout()
        self.complexButtons.setSpacing(0)
        self.complexButtons.setObjectName("complexButtons")
        self.ann_complex = QtWidgets.QPushButton(self.widget)
        self.ann_complex.setMinimumSize(QtCore.QSize(0, 70))
        self.ann_complex.setIconSize(QtCore.QSize(20, 20))
        self.ann_complex.setObjectName("ann_complex")

        self.ann_complex.clicked.connect(lambda: self.btn_ann("complex"))

        self.complexButtons.addWidget(self.ann_complex)


        self.complexVBox.addLayout(self.complexButtons)
        self.HBox.addLayout(self.complexVBox)
        self.MainVBox.addWidget(self.TypesFrame)
        self.SimulationFrame = QtWidgets.QFrame(self.layoutWidget)
        self.SimulationFrame.setStyleSheet("background-color: rgb(255, 23, 205);")
        self.SimulationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SimulationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SimulationFrame.setObjectName("SimulationFrame")
        self.widget1 = QtWidgets.QWidget(self.SimulationFrame)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 1921, 631))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.before = QtWidgets.QLabel(self.widget1)
        self.before.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.before.setAlignment(QtCore.Qt.AlignCenter)
        self.before.setObjectName("before")
        self.horizontalLayout.addWidget(self.before)
        self.after = QtWidgets.QLabel(self.widget1)
        self.after.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.after.setAlignment(QtCore.Qt.AlignCenter)
        self.after.setObjectName("after")
        self.horizontalLayout.addWidget(self.after)
        self.MainVBox.addWidget(self.SimulationFrame)
        self.ExecutionFrame = QtWidgets.QFrame(self.layoutWidget)
        self.ExecutionFrame.setStyleSheet("background-color: rgb(34, 255, 108);")
        self.ExecutionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ExecutionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ExecutionFrame.setObjectName("ExecutionFrame")
        self.layoutWidget_6 = QtWidgets.QWidget(self.ExecutionFrame)
        self.layoutWidget_6.setGeometry(QtCore.QRect(0, 0, 1921, 72))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.HBox3 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.HBox3.setContentsMargins(0, 0, 0, 0)
        self.HBox3.setSpacing(0)
        self.HBox3.setObjectName("HBox3")
        self.simul_before = QtWidgets.QPushButton(self.layoutWidget_6)
        self.simul_before.setMinimumSize(QtCore.QSize(0, 70))
        self.simul_before.setObjectName("simul_before")

        self.simul_before.clicked.connect(self.btn_simul_before)

        self.HBox3.addWidget(self.simul_before)
        self.show_vis = QtWidgets.QPushButton(self.layoutWidget_6)
        self.show_vis.setMinimumSize(QtCore.QSize(0, 70))
        self.show_vis.setObjectName("show_vis")

        self.show_vis.clicked.connect(self.btn_vis)

        self.HBox3.addWidget(self.show_vis)
        self.simul_after = QtWidgets.QPushButton(self.layoutWidget_6)
        self.simul_after.setMinimumSize(QtCore.QSize(0, 70))
        self.simul_after.setObjectName("simul_after")

        self.simul_after.clicked.connect(self.btn_simul_after)

        self.HBox3.addWidget(self.simul_after)
        self.MainVBox.addWidget(self.ExecutionFrame)
        self.MainVBox.setStretch(0, 15)
        self.MainVBox.setStretch(1, 15)
        self.MainVBox.setStretch(2, 63)
        self.MainVBox.setStretch(3, 7)

        self.intersection = "3-way"
        self.model = "ANN"

        self.before_gif = QtWidgets.QLabel(self.before)
        self.before_movie = QtGui.QMovie(PATH + r"\GUI\GIFS\Normal\3-way.gif")
        self.before_gif.setMovie(self.before_movie)
        self.before_movie.setScaledSize(QtCore.QSize(961,631))
        self.before_movie.start()

        self.after_gif = QtWidgets.QLabel(self.after)
        self.after_movie = QtGui.QMovie(PATH + r"\GUI\GIFS\ANN\3-way.gif")
        self.after_gif.setMovie(self.after_movie)
        self.after_movie.setScaledSize(QtCore.QSize(960,631))
        self.after_movie.start()

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def btn_simul_before(self):
        os.startfile(PATH + r"\ANN\%s\intersection\sumo_config.sumocfg" %(self.intersection))

    def btn_simul_after(self):
        goto = PATH + r"\%s\%s" %(self.model, self.intersection)
        os.system("cd " + goto + "&& python testing_main.py")

    def btn_vis(self):
        os.startfile(PATH + r"\%s\%s\models\model_1\plot_delay.png" %(self.model, self.intersection))

    def btn_cnn(self, intersection):
        self.intersection = intersection
        self.model = "CNN"
        self.before_movie = QtGui.QMovie(PATH + r"\GUI\GIFS\Normal\%s.gif" %(intersection))
        self.before_gif.setMovie(self.before_movie)
        self.before_movie.setScaledSize(QtCore.QSize(961,630))
        self.before_movie.start()

        self.after_movie = QtGui.QMovie(PATH + r"\GUI\GIFS\CNN\%s.gif" %(intersection))
        self.after_gif.setMovie(self.after_movie)
        self.after_movie.setScaledSize(QtCore.QSize(960,630))
        self.after_movie.start()

    def btn_ann(self, intersection):
        self.intersection = intersection
        self.model = "ANN"
        self.before_movie = QtGui.QMovie(PATH + r"\GUI\GIFS\Normal\%s.gif" %(intersection))
        self.before_gif.setMovie(self.before_movie)
        self.before_movie.setScaledSize(QtCore.QSize(961,630))
        self.before_movie.start()

        self.after_movie = QtGui.QMovie(PATH + r"\GUI\GIFS\ANN\%s.gif" %(intersection))
        self.after_gif.setMovie(self.after_movie)
        self.after_movie.setScaledSize(QtCore.QSize(960,630))
        self.after_movie.start()

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowIcon(QtGui.QIcon('PES.jpg'))
        main.setWindowTitle(_translate("main", "Intelligent Traffic Light System"))
        self.title.setText(_translate("main", "Smart Traffic Light Controller using Deep Reinforcement Learning"))
        self.intersection_3.setText(_translate("main", "3-way Intersection"))
        self.ann_3.setText(_translate("main", "ANN"))
        self.cnn_3.setText(_translate("main", "CNN"))
        self.intersection_4.setText(_translate("main", "4-way Intersection"))
        self.ann_4.setText(_translate("main", "ANN"))
        self.cnn_4.setText(_translate("main", "CNN"))
        self.intersection_5.setText(_translate("main", "5-way Intersection"))
        self.ann_5.setText(_translate("main", "ANN"))
        self.cnn_5.setText(_translate("main", "CNN"))
        self.intersection_double.setText(_translate("main", "Double Intersection"))
        self.ann_double.setText(_translate("main", "ANN"))
        self.cnn_double.setText(_translate("main", "CNN"))
        self.intersection_complex.setText(_translate("main", "Complex Intersection"))
        self.ann_complex.setText(_translate("main", "ANN"))
        self.before.setText(_translate("main", "BEFORE"))
        self.after.setText(_translate("main", "AFTER"))
        self.simul_before.setText(_translate("main", "Run Simulation"))
        self.show_vis.setText(_translate("main", "Show Visualisation"))
        self.simul_after.setText(_translate("main", "Run Simulation"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QWidget()
    ui = Ui_main()
    ui.setupUi(main)
    main.showMaximized()
    sys.exit(app.exec_())
